Teacher.destroy_all
teacher1 = Teacher.create(last_name: "smith", years_of_experience: 4)
teacher2 = Teacher.create(last_name: "samson", years_of_experience: 6)
teacher3 = Teacher.create(last_name: "McCarthy", years_of_experience: 6)

Student.destroy_all
student1 = Student.create(first_name: "fn1", last_name: "ln1")
student2 = Student.create(first_name: "fn2", last_name: "ln2")
student3 = Student.create(first_name: "fn3", last_name: "ln3")
student4 = Student.create(first_name: "fn4", last_name: "ln4")
student5 = Student.create(first_name: "fn5", last_name: "ln5")
student6 = Student.create(first_name: "fn6", last_name: "ln6")
student7 = Student.create(first_name: "fn7", last_name: "ln7")
student8 = Student.create(first_name: "fn8", last_name: "ln8")
student9 = Student.create(first_name: "fn9", last_name: "ln9")
student10 = Student.create(first_name: "fn10", last_name: "ln10")

GradeLevel.destroy_all
GradeLevel.create(name: "nineth", teacher_id: teacher1.id, student_id: student1.id)
GradeLevel.create(name: "nineth", teacher_id: teacher1.id, student_id: student2.id)
GradeLevel.create(name: "nineth", teacher_id: teacher1.id, student_id: student3.id)
GradeLevel.create(name: "nineth", teacher_id: teacher1.id, student_id: student4.id)
GradeLevel.create(name: "nineth", teacher_id: teacher1.id, student_id: student5.id)
GradeLevel.create(name: "nineth", teacher_id: teacher2.id, student_id: student1.id)
GradeLevel.create(name: "nineth", teacher_id: teacher2.id, student_id: student2.id)
GradeLevel.create(name: "nineth", teacher_id: teacher2.id, student_id: student3.id)
GradeLevel.create(name: "nineth", teacher_id: teacher2.id, student_id: student4.id)
GradeLevel.create(name: "nineth", teacher_id: teacher2.id, student_id: student5.id)
GradeLevel.create(name: "tenth", teacher_id: teacher3.id, student_id: student6.id)
GradeLevel.create(name: "tenth", teacher_id: teacher3.id, student_id: student7.id)
GradeLevel.create(name: "tenth", teacher_id: teacher3.id, student_id: student8.id)
GradeLevel.create(name: "tenth", teacher_id: teacher3.id, student_id: student9.id)
GradeLevel.create(name: "tenth", teacher_id: teacher3.id, student_id: student10.id)
GradeLevel.create(name: "tenth", teacher_id: teacher2.id, student_id: student6.id)
GradeLevel.create(name: "tenth", teacher_id: teacher2.id, student_id: student7.id)
GradeLevel.create(name: "tenth", teacher_id: teacher2.id, student_id: student8.id)
GradeLevel.create(name: "tenth", teacher_id: teacher2.id, student_id: student9.id)
GradeLevel.create(name: "tenth", teacher_id: teacher2.id, student_id: student10.id)